// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit!  //
// (hand-written equivalent — 3-instruction PIO prog)  //
// -------------------------------------------------- //
//
// serial_rx: Samples CC1200 SERIAL_RX on SERIAL_CLK rising edge.
//
// CC1200 synchronous serial mode outputs:
//   GPIO0 → SERIAL_RX  (data, directly connected to Pico GP7)
//   GPIO2 → SERIAL_CLK (clock, directly connected to Pico GP9)
//
// PIO samples SERIAL_RX on each rising CLK edge, autopushes every 8 bits.
//
// .program serial_rx
// .wrap_target
//     wait 1 pin 1    ; wait for SERIAL_CLK high  (pin base+1 = GP9)
//     in pins, 1      ; shift SERIAL_RX into ISR   (pin base+0 = GP7)
//     wait 0 pin 1    ; wait for SERIAL_CLK low    (complete one bit period)
// .wrap

#pragma once

#include "hardware/pio.h"

static const uint16_t serial_rx_program_instructions[] = {
    //     .wrap_target
    0x20a1, // wait 1 pin 1
    0x4001, // in   pins, 1
    0x2021, // wait 0 pin 1
    //     .wrap
};

static const struct pio_program serial_rx_program = {
    .instructions = serial_rx_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config serial_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + 0, offset + 2);  // wrap_target=0, wrap=2
    return c;
}

/**
 * Initialise PIO state machine for CC1200 synchronous serial RX.
 *
 * @param pio       PIO instance (pio0 or pio1)
 * @param sm        State machine index (0-3)
 * @param offset    Program load offset (from pio_add_program)
 * @param pin_rx    GPIO for SERIAL_RX data (CC1200 GPIO0 → Pico GP7)
 * @param pin_clk   GPIO for SERIAL_CLK    (CC1200 GPIO2 → Pico GP9)
 */
static inline void serial_rx_program_init(PIO pio, uint sm, uint offset,
                                           uint pin_rx, uint pin_clk) {
    // Configure pins as PIO inputs
    pio_gpio_init(pio, pin_rx);
    pio_gpio_init(pio, pin_clk);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_rx, 1, false);   // RX = input
    pio_sm_set_consecutive_pindirs(pio, sm, pin_clk, 1, false);  // CLK = input

    pio_sm_config c = serial_rx_program_get_default_config(offset);

    // IN pin base = pin_rx (so `in pins, 1` reads GP7)
    // Wait pin base must also start at pin_rx so `wait X pin 1` reads GP9
    // This requires pin_clk == pin_rx + 1, which we assert at compile time.
    // If pins are non-adjacent, we'd need a different approach, but they are
    // (GP7 and GP9 differ by 2 — so we use pin_rx as base and offset=2 won't
    //  work with `wait X pin 1`).
    //
    // Actually: `wait` and `in` share the same pin mapping group.
    // pin base = pin_rx means pin 0 = GP7, pin 1 = GP8, pin 2 = GP9.
    // We need `wait X pin 2` for GP9 and `in pins, 1` for GP7.
    // But our PIO program uses `wait X pin 1` — so we need pin_clk = pin_rx+1.
    //
    // GP7 (RX) and GP9 (CLK) differ by 2, not 1. Fix: use pin_rx=GP7 as base,
    // and modify the PIO instructions at runtime to use the correct pin offset.
    //
    // Simpler: set in_base to pin_rx. The `wait` instruction uses the same
    // pin mapping. pin index 0 = pin_rx (GP7), so pin index 2 = GP9.
    // We just need the PIO program to use `wait X pin 2` instead of `wait X pin 1`.
    // Since we're providing the program as an array, patch it here:
    //
    // Note: For GP7/GP9 (offset=2), we patch the wait instructions.
    // For adjacent pins (offset=1), the original instructions work.

    uint clk_offset = pin_clk - pin_rx;  // typically 2 for GP7→GP9

    // Patch PIO instructions with correct pin offset for SERIAL_CLK
    // wait 1 pin N → 0x20a0 | N   (N = clk_offset)
    // wait 0 pin N → 0x2020 | N
    // in pins, 1   → 0x4001 (unchanged)
    uint16_t patched[3];
    patched[0] = 0x20a0 | (clk_offset & 0x1F);  // wait 1 pin <clk_offset>
    patched[1] = 0x4001;                          // in pins, 1
    patched[2] = 0x2020 | (clk_offset & 0x1F);  // wait 0 pin <clk_offset>

    // Write patched instructions into PIO instruction memory
    for (uint i = 0; i < 3; i++) {
        pio->instr_mem[offset + i] = patched[i];
    }

    sm_config_set_in_pins(&c, pin_rx);  // IN pin base = GP7

    // Shift left, autopush every 8 bits → bytes in RX FIFO
    sm_config_set_in_shift(&c, false, true, 8);

    // No clock divider — PIO runs at sysclk, gated by wait instructions
    sm_config_set_clkdiv(&c, 1.0f);

    pio_sm_init(pio, sm, offset, &c);
    // Don't enable yet — caller does pio_sm_set_enabled() when ready
}
