[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

build_flags =
    -DDEBUG_RP2040_PORT=Serial
    ; Expose raw Pico SDK SPI + clock APIs alongside Arduino
    -DPICO_DEFAULT_UART=0
    -DPICO_DEFAULT_UART_TX_PIN=0
    -DPICO_DEFAULT_UART_RX_PIN=1

lib_deps =
    adafruit/Adafruit NeoPixel@^1.12

; Upload by dragging UF2 onto RPI-RP2 drive
upload_protocol = mbed

monitor_speed = 115200

; Copy UF2 to repo root after build
extra_scripts = post:copy_uf2.py
